Push financial data into apply api on submission of application
SkillsFundingAgency/das-apply-service pull request #634
Opened 2020-12-10 15:29 UTC by chrisfoster76

2020-12-15 16:06 UTC, martin-hornsby commented on src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
> +                var m = ex.Message;
Were you expecting to log this or use it for debug?

2020-12-15 16:06 UTC, martin-hornsby commented on src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
> +
bit of whitespace here

2020-12-15 16:06 UTC, martin-hornsby submitted a review, later dismissed

2020-12-16 08:45 UTC, martin-hornsby submitted a review, later dismissed

2020-12-16 13:36 UTC, martin-hornsby submitted a review, later dismissed

2020-12-21 08:52 UTC, martin-hornsby requested changes

2020-12-21 08:52 UTC, martin-hornsby commented on src/SFA.DAS.ApplyService.Application/Apply/Roatp/RoatpPreambleQuestionBuilder.cs
> +        public static string Borrowings = "Borrowings";
As mentioned. Best to prefix these in QnA so they have context in the wider context of things

2020-12-21 08:52 UTC, martin-hornsby commented on src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
> +                            CASE s.NotRequired WHEN 'false' THEN 'Not exempt' ELSE 'Exempt' END AS DeclaredInApplication,
Isn't this a bit field in the database? Would have expected 0

2020-12-21 08:55 UTC, MarkFCain submitted a review, later dismissed

2020-12-21 08:56 UTC, martin-hornsby commented on src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
> +                            CASE s.NotRequired WHEN 'false' THEN 'Not exempt' ELSE 'Exempt' END AS DeclaredInApplication,
please ignore, it's doing a transform in the Cross Apply

2020-12-21 08:57 UTC, martin-hornsby approved these changes

2020-12-24 11:59 UTC, martin-hornsby approved these changes

2020-12-24 11:59 UTC, merged