Apr 2127 applicant appeal message
SkillsFundingAgency/das-apply-service pull request #696
Opened 2021-02-23 15:14 UTC by chrisfoster76

2021-02-23 15:49 UTC, MarkFCain approved these changes

2021-02-23 16:03 UTC, martin-lush requested changes

2021-02-25 07:45 UTC, chrisfoster76 commented on src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/OversightHandlerTests/UploadAppealFileCommandHandlerTests.cs
> +            result.ContentType = "application.pdf";
yep

2021-02-25 07:46 UTC, chrisfoster76 commented on src/SFA.DAS.ApplyService.Application/Apply/Oversight/RemoveAppealFileCommandHandler.cs
> +                throw new InvalidOperationException($"Appeal upload {request.FileId} does not belong to Application {request.ApplicationId}");
The exception is thrown and logged

2021-02-25 08:11 UTC, martin-lush approved these changes

2021-03-02 10:26 UTC, MarkFCain submitted a review, later dismissed

2021-03-02 14:15 UTC, martin-lush submitted a review, later dismissed

2021-03-02 14:16 UTC, MarkFCain approved these changes

2021-03-02 14:21 UTC, martin-lush approved these changes

2021-03-02 14:23 UTC, merged