CSP-325-DotCore6Migration-apply
SkillsFundingAgency/das-apply-service pull request #978
Opened 2022-10-31 16:55 UTC by raviudari01

2022-11-01 15:05 UTC, MarkFCain commented on src/SFA.DAS.ApplyService.Data/OrganisationRepository.cs
> -        public async Task UpdateOrganisation(Guid organisationId, Guid userId)
I wouldn't make any code changes, can you put this back?

2022-11-01 15:09 UTC, MarkFCain requested changes
Can you reset the index name back to what it was, and put back in the method OrganisationRepository.UpdateOrganisation

2022-11-01 15:17 UTC, MarkFCain submitted a review, later dismissed

2022-11-01 15:25 UTC, DevenKShah reviewed
Developer exception page needs to be enabled.

2022-11-01 15:25 UTC, DevenKShah commented on src/SFA.DAS.ApplyService.Data/SFA.DAS.ApplyService.Data.csproj
> -        <Version>1.50.5</Version>
Move version on the same line

2022-11-01 15:25 UTC, DevenKShah commented on src/SFA.DAS.ApplyService.Web/Views/Home/Error.cshtml
> -            @if (HostingEnvironment.IsDevelopment())
We removed this with agreement that in the startup we will configure to go to this page only if it is on hosted environment, we still need to see `DeveloperExceptionPage` when debugging. I have not found any config changes in this regards?

2022-11-03 10:43 UTC, DevenKShah submitted a review, later dismissed

2022-11-03 10:43 UTC, DevenKShah commented on src/SFA.DAS.ApplyService.Web/Startup.cs
> +        private readonly IWebHostEnvironment _env;
Do we need two variables for the same thing?

2022-11-04 15:18 UTC, MarkFCain submitted a review, later dismissed

2022-11-04 16:39 UTC, HussainsGitHub approved these changes

2022-11-07 14:10 UTC, DevenKShah approved these changes

2022-11-07 14:13 UTC, merged